#!/usr/bin/python
import sys
from StringIO import StringIO

buf = StringIO()

def push_number(x):
    # push number
    buf.write("  ")
    # positive sign
    buf.write(" ")
    for c in bin(x)[2:].zfill(8).lstrip("0"):
        if c == "0":
            # zero
            buf.write(" ")
        else:
            # one
            buf.write("\t")
    # end parameter
    buf.write("\n")

def print_top_of_stack():
    # print top of stack
    buf.write("\t\n  ")

def end_program():
    buf.write("\n\n\n")

with file("full-lyrics.txt") as f:
    for c in f.read():
        push_number(ord(c))
        print_top_of_stack()
    end_program()

sys.stdout.write(buf.getvalue())
