#!/usr/bin/python
import sys
from StringIO import StringIO
from whitespace import WhitespaceAssemblerParser, WhitespaceAssembler

parser = WhitespaceAssemblerParser()
asm = WhitespaceAssembler()

with file("full-lyrics.txt") as f:
    data = f.read()
    for c in reversed(data):
        asm.push(ord(c)-ord("A"))

    asm.push(len(data))
    asm.call("write_buffer")
    asm.halt()
    lib = file("xmas5-ws/write_buffer.wsa").read()
    asm.assemble(parser.parse(lib))

sys.stdout.write(asm.get_result())
